version: '3.4'

services:
  you:
    image: you
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn betterapi_docker.src/main:app --host 0.0.0.0 --port 80"]
    ports:
      - 80:80
      - 5678:5678
